import mongoose from "mongoose";
import settings from "../../../schemas/settings.js";

export default {
	name: "guildCreate",
	async execute(event) {
		let settingsData = await settings.findOne({server: event.id});

		if (!settingsData) {
			settingsData = new settings({
				_id: new mongoose.Types.ObjectId(),
				server: event.id,
				settings: {
					prefixes: ["?", `<@${process.env.clientID}>`],
					ignoreChannels: [],
					ignoreChannelsInvert: false,
					ignoreRoles: [],
					ignoreRolesInvert: false,
					ignoreUsers: [],
					ignoreUsersInvert: false,
					modRoles: [],
					modUsers: [],
				},
				commands: {
					global: {
						ignoreOverWritesChannels: [],
						ignoreOverWritesChannelsInvert: false,
						ignoreOverWritesRoles: [],
						ignoreOverWritesRolesInvert: false,
						ignoreOverWritesUsers: [],
						ignoreOverWritesUsersInvert: false,
					},
					commands: [],
				},
				botCustomiser: {
					changeInterval: 5,
					array: [
						{
							nickname: "🌳 Slime Bot",
							iconURL: `https://cdn.discordapp.com/avatars/${process.env.clientID}/b2248219efe2ac802d1af124b7d1a887.webp?size=4096`,
							status: "online",
							activityType: "",
							activityText: "",
						},
					],
				},
				levels: {
					min: 10,
					max: 50,
					cooldown: 30,
					message: {
						send: "Current Channel",
						message: "{user.ping} has reached {user.level}!",
						embeds: [],
						images: [],
					},
					levelCard: {},
					roleRewards: {
						stack: false,
						rewards: [],
					},
					xpRate: 1,
					boosters: {},
					maxLevel: null,
					ignoreRoles: [],
					ignoreRolesInvert: false,
					ignoreChannels: [],
					ignoreChannelsInvert: false,
					ignoreUsers: [],
					ignoreUsersInvert: false,
				},
				counting: [],
				verification: {enabled: false},
				reactionRoles: [],
				starboard: {
					channel: "",
					stars: 3,
					emoji: "⭐",
					link: true,
					selfstar: true,
					ignoreChannels: [],
					ignoreChannelsInvert: false,
					ignoreRoles: [],
					ignoreRolesInvert: false,
					ignoreUsers: [],
					ignoreUsersInvert: false,
				},
				inviteManager: {enabled: false, channel: ""},
				suggestions: {
					enabled: false,
					suggestionChannel: "",
					decisionChannel: "",
					ignoreChannels: [],
					ignoreChannelsInvert: false,
					ignoreRoles: [],
					ignoreRolesInvert: false,
					ignoreUsers: [],
					ignoreUsersInvert: false,
					dm: true,
					edit: true,
					anonymous: false,
				},
				tickets: [],
				modmail: {enabled: false},
				counters: [],
				welcome: {
					channelMessage: {
						enabled: false,
						channel: "",
						content: "Welcome {user.ping} to {guild.name}!",
						embeds: [],
						images: [
							{
								name: "Welcome Image",
								layers: [
									{
										text: "https://cdn.discordapp.com/attachments/1020058739526619186/1048600817009164338/background.png",
										x: 0,
										y: 0,
										width: 1070,
										height: 484,
										type: "image",
									},
									{
										text: "{interaction.user.username} has joined {guild.name}",
										colour: "#ffffff",
										font: "40px Arial",
										x: "<center>",
										y: 320,
										type: "text",
									},
									{
										text: "Member #{member.count}",
										colour: "#a1a1a1",
										font: "30px Arial",
										x: "<center>",
										y: 370,
										type: "text",
									},
								],
								width: 1070,
								height: 484,
							},
						],
					},
					directMessage: {
						enabled: false,
						content:
							"Welcome to {guild.name}! Make sure to read the information and rules!",
						embeds: [],
						images: [
							{
								name: "Welcome DM Message",
								layers: [
									{
										text: "https://cdn.discordapp.com/attachments/1020058739526619186/1048600817009164338/background.png",
										x: 0,
										y: 0,
										width: 1070,
										height: 484,
										type: "image",
									},
									{
										text: "Welcome to {guild.name}!",
										colour: "#ffffff",
										font: "40px Arial",
										x: "<center>",
										y: 320,
										type: "text",
									},
									{
										text: "Member #{member.count}",
										colour: "#a1a1a1",
										font: "30px Arial",
										x: "<center>",
										y: 370,
										type: "text",
									},
								],
								width: 1070,
								height: 484,
							},
						],
					},
				},
				goodbye: {
					enabled: false,
					channel: "",
					content: "{interaction.user.username} has left the server.",
					embeds: [],
					images: [
						{
							name: "Goodbye Image",
							layers: [
								{
									text: "https://cdn.discordapp.com/attachments/1020058739526619186/1048600817009164338/background.png",
									x: 0,
									y: 0,
									width: 1070,
									height: 484,
									type: "image",
								},
								{
									text: "{interaction.user.username} has left the server.",
									colour: "#ffffff",
									font: "40px Arial",
									x: "<center>",
									y: 320,
									type: "text",
								},
								{
									text: "We hope to see you again.",
									colour: "#a1a1a1",
									font: "30px Arial",
									x: "<center>",
									y: 370,
									type: "text",
								},
							],
							width: 1070,
							height: 484,
						},
					],
				},
				boosting: {
					boost: {
						enabled: false,
						channel: "",
						content: "{user.ping} has boosted the server!",
						embeds: [],
						images: [
							{
								name: "Boost Image",
								layers: [
									{
										text: "https://cdn.discordapp.com/attachments/1020058739526619186/1048927725391466586/boost.png",
										x: 0,
										y: 0,
										width: 1070,
										height: 484,
										type: "image",
									},
									{
										text: "{interaction.user.username} has boosted {guild.name}!",
										colour: "#ffffff",
										font: "40px Arial",
										x: "<center>",
										y: 320,
										type: "text",
									},
									{
										text: "Thank you for your support!",
										colour: "#a1a1a1",
										font: "30px Arial",
										x: "<center>",
										y: 370,
										type: "text",
									},
								],
								width: 1070,
								height: 484,
							},
						],
					},
					unBoost: {
						enabled: false,
						channel: "",
						content: "Welcome {user.ping} to {guild.name}!",
						embeds: [],
						images: [
							{
								name: "Unboost Image",
								layers: [
									{
										text: "https://cdn.discordapp.com/attachments/1020058739526619186/1048927725391466586/boost.png",
										x: 0,
										y: 0,
										width: 1070,
										height: 484,
										type: "image",
									},
									{
										text: "{interaction.user.username} has unboosted {guild.name}.",
										colour: "#ffffff",
										font: "40px Arial",
										x: "<center>",
										y: 320,
										type: "text",
									},
									{
										text: "Thank you for your support.",
										colour: "#a1a1a1",
										font: "30px Arial",
										x: "<center>",
										y: 370,
										type: "text",
									},
								],
								width: 1070,
								height: 484,
							},
						],
					},
				},
				automod: {
					rules: {
						badwords: {},
						repeatedText: {},
						serverInvites: {},
						links: {},
						caps: {},
						emojis: {},
						spoilers: {},
						pings: {},
						zalgo: {},
						antispam: {},
					},
					actions: [],
					restrictedChannels: {channels: [], sendMessage: false},
					ignoreMods: true,
					ignoreBots: true,
					ignoreChannels: [],
					ignoreChannelsInvert: false,
					ignoreRoles: [],
					ignoreRolesInvert: false,
					ignoreUsers: [],
					ignoreUsersInvert: false,
				},
				logs: {
					ignoreChannels: [],
					ignoreChannelsInvert: false,
					ignoreRoles: [],
					ignoreRolesInvert: false,
					ignoreUsers: [],
					ignoreUsersInvert: false,
					ignoreBots: false,
					ignoreMods: false,
					logs: {
						memberBanned: {},
						memberUnbanned: {},
						memberKicked: {},
						timeout: {},
						memberJoin: {},
						memberLeave: {},
						channelCreated: {},
						channelDeleted: {},
						channelUpdated: {},
						channelPermsUpdated: {},
						roleCreated: {},
						roleDeleted: {},
						roleUpdated: {},
						roleGiven: {},
						roleRemoved: {},
						messageDeleted: {},
						messagesPurged: {},
						messageEdited: {},
						voiceJoin: {},
						voiceLeave: {},
						voiceMove: {},
						voiceForceMove: {},
						voiceKick: {},
						voiceState: {},
						nameChange: {},
						nickNameChange: {},
						avatarChange: {},
						modCommandUse: {},
						inviteCreated: {},
						inviteRemoved: {},
						serverUpdated: {},
						emojiAdded: {},
						emojiRemoved: {},
					},
				},
				privateVC: {channel: "", category: ""},
				youtube: [],
				twitch: [],
				twitter: [],
				reddit: [],
				instagram: [],
				streaming: {
					enabled: false,
					channel: "",
					message: {
						content: "",
						embeds: [],
						images: [],
						role: "",
						ignoreRoles: [],
						ignoreRolesInvert: false,
						ignoreUsers: [],
						ignoreUsersInvert: false,
					},
				},
				forms: [],
				stickyMessages: [],
				customCommands: [],
				responder: [],
			});

			for (const rule in settingsData.automod.rules) {
				settingsData.automod[rule] = {
					enabled: false,
					ignoreChannels: [],
					ignoreChannelsInvert: null,
					ignoreRoles: [],
					ignoreRolesInvert: null,
					ignoreUsers: [],
					ignoreUsersInvert: null,
					ignoreMods: null,
					ignoreBots: null,
				};
			}

			for (const log in settingsData.logs.logs) {
				settingsData.logs[log] = {
					enabled: false,
					channel: "",
					colour: "2f3136",
					ignoreChannels: [],
					ignoreChannelsInvert: null,
					ignoreRoles: [],
					ignoreRolesInvert: null,
					ignoreUsers: [],
					ignoreUsersInvert: null,
					ignoreBots: null,
					ignoreMods: null,
				};
			}

			await settingsData.save();
		}
	},
};
